# file: .github/workflows/hello-world.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # sayHello – произвольно выбранное имя задания
  # их может быть больше одного
  sayHello: make say-hello